export const adhigaramTitles: Record<string, string> = {
    "கடவுள் வாழ்த்து": "The Praise of God",
    "வான்சிறப்பு": "The Excellence of Rain",
    "நீத்தார் பெருமை": "The Greatness of Ascetics",
    "அறன் வலியுறுத்தல்": "Assertion of the Strength of Virtue",
    "இல்வாழ்க்கை": "Domestic Life",
    "வாழ்க்கைத் துணைநலம்": "The Worth of a Wife",
    "புதல்வரைப் பெறுதல்": "The Obtaining of Sons",
    "அன்புடைமை": "Possession of Love",
    "விருந்தோம்பல்": "Cherishing Guests",
    "இனியவை கூறல்": "Utterance of Pleasant Words",
    "செய்நன்றி அறிதல்": "Gratitude",
    "நடுவு நிலைமை": "Impartiality",
    "அடக்க முடைமை": "Possession of Self-restraint",
    "ஒழுக்க முடைமை": "Possession of Decorum",
    "பிறனில் விழையாமை": "Not coveting another's Wife",
    "பொறையுடைமை": "Possession of Patience, Forbearance",
    "அழுக்காறாமை": "Not Envying",
    "வெஃகாமை": "Not Coveting",
    "புறங்கூறாமை": "Not Backbiting",
    "பயனில சொல்லாமை": "Against Vain Speaking",
    "தீவினையச்சம்": "Dread of Evil Deeds",
    "ஒப்புரவறிதல்": "Duty to Society",
    "ஈகை": "Giving",
    "புகழ்": "Renown",
    "அருளுடைமை": "Compassion",
    "புலாலான் மறுத்தல்": "Abstinence from Flesh",
    "தவம்": "Penance",
    "கூடாவொழுக்கம்": "Imposture",
    "கள்ளாமை": "Absence of Fraud",
    "வாய்மை": "Veracity",
    "வெகுளாமை": "Restraint of Anger",
    "இன்னா செய்யாமை": "Not doing Evil",
    "கொல்லாமை": "Not Killing",
    "நிலையாமை": "Instability",
    "துறவு": "Renunciation",
    "மெய்யுணர்தல்": "Truth-Consciousness",
    "அவாஅறுத்தல்": "Curbing of Desire",
    "ஊழ்": "Fate",
    "இறைமாட்சி": "The Greatness of a King",
    "கல்வி": "Learning",
    "கல்லாமை": "Ignorance",
    "கேள்வி": "Hearing",
    "அறிவுடைமை": "Possession of Knowledge",
    "குற்றம் கடிதல்": "Correction of Faults",
    "பெரியாரைத் துணைக்கோடல்": "Seeking the Aid of Great Men",
    "சிற்றினம் சேராமை": "Avoiding mean Associations",
    "தெரிந்து செயல்வகை": "Acting after due Consideration",
    "வலியறிதல்": "Judging of Strength",
    "காலமறிதல்": "Knowing the fitting Time",
    "இடனறிதல்": "Knowing the Place",
    "தெரிந்து தெளிதல்": "Selection and Confidence",
    "தெரிந்து வினையாடல்": "Selection and Employment",
    "சுற்றந் தழால்": "Cherishing Kisnmen",
    "பொச்சாவாமை": "Unforgetfulness",
    "செங்கோன்மை": "The Right Sceptre",
    "கொடுங்கோன்மை": "The Cruel Sceptre",
    "வெருவந்த செய்யாமை": "Absence of Terrorism",
    "கண்ணோட்டம்": "Benignity",
    "ஒற்றாடல்": "Detectives",
    "ஊக்கம் உடைமை": "Energy",
    "மடியின்மை": "Unsluggishness",
    "ஆள்வினையுடைமை": "Manly Effort",
    "இடுக்கண் அழியாமை": "Hope in Mishap",
    "அமைச்சு": "The Office of Minister of state",
    "சொல்வன்மை": "Power of Speech",
    "வினைத் தூய்மை": "Purity of Action",
    "வினைத்திட்பம்": "Power of Action",
    "வினைசெயல்வகை": "Modes of Action",
    "தூது": "The Envoy",
    "மன்னரைச் சேர்ந்தொழுகல்": "Conduct in the Presence of the King",
    "குறிப்பறிதல்": "Knowledge of Indications / Reading of the Signs",
    "அவையறிதல்": "Knowledge of the Council Chamber",
    "அவை அஞ்சாமை": "Not to fear the Council",
    "நாடு": "The Land",
    "அரண்": "The Fortification",
    "பொருள்செயல்வகை": "Way of Accumulating Wealth",
    "படைமாட்சி": "The Excellence of an Army",
    "படைச்செருக்கு": "Military Spirit",
    "நட்பு": "Friendship",
    "நட்பாராய்தல்": "Investigation in forming Friendships",
    "பழைமை": "Intimacy",
    "தீநட்பு": "Evil Friendship",
    "கூடாநட்பு": "Unreal Friendship",
    "பேதைமை": "Folly",
    "புல்லறிவாண்மை": "Ignorance",
    "இகல்": "Hostility",
    "பகைமாட்சி": "The Might of Hatred",
    "பகைத்திறம் தெரிதல்": "Knowing the Quality of Hate",
    "உட்பகை": "Internal Enmity",
    "பெரியாரைப் பிழையாமை": "Not Offending the Great",
    "பெண்வழிச் சேறல்": "Being led by Women",
    "வரைவின் மகளிர்": "Wanton Women",
    "கள்ளுண்ணாமை": "Not Drinking Palm-Wine",
    "சூது": "Gambling",
    "மருந்து": "Medicine",
    "குடிமை": "Nobility",
    "மானம்": "Honour",
    "பெருமை": "Greatness",
    "சான்றாண்மை": "Perfectness",
    "பண்புடைமை": "Courtesy",
    "நன்றியில் செல்வம்": "Wealth without Benefaction",
    "நாணுடைமை": "Possession of Shame",
    "குடிசெயல்வகை": "The Way of Maintaining the Family",
    "உழவு": "Farming",
    "நல்குரவு": "Poverty",
    "இரவு": "Mendicancy",
    "இரவச்சம்": "Dread of Mendicancy",
    "கயமை": "Baseness",
    "தகைஅணங்குறுத்தல்": "The Tormenting look",
    "புணர்ச்சி மகிழ்தல்": "Rejoicing in the Embrace",
    "நலம் புனைந்து உரைத்தல்": "Praise of her Beauty",
    "காதற் சிறப்புரைத்தல்": "Declaration of Love's special Excellence",
    "நாணுத் துறவுரைத்தல்": "The Abandonment of Reserve",
    "அலரறிவுறுத்தல்": "The Announcement of Rumour",
    "பிரிவாற்றாமை": "Separation: unendurable",
    "படர்மெலிந்திரங்கல்": "Complainings",
    "கண்விதுப்பழிதல்": "Eyes consumed with Grief",
    "பசப்புறுபருவரல்": "The Pallid Hue",
    "தனிப்படர் மிகுதி": "The Solitary Anguish",
    "நினைந்தவர் புலம்பல்": "Sad Memories",
    "கனவுநிலை உரைத்தல்": "The Visions of the Night",
    "பொழுதுகண்டு இரங்கல்": "Lamentations at Eventide",
    "உறுப்புநலன் அழிதல்": "Wasting Away",
    "நெஞ்சொடு கிளத்தல்": "Soliloquy",
    "நிறையழிதல்": "Reserve Overcome",
    "அவர்வயின் விதும்பல்": "Mutual Desire",
    "குறிப்பறிவுறுத்தல்": "The Reading of the Signs",
    "புணர்ச்சி விதும்பல்": "Desire for Reunion",
    "நெஞ்சொடு புலத்தல்": "Expostulation with Oneself",
    "புலவி": "Pouting",
    "புலவி நுணுக்கம்": "Feigned Anger",
    "ஊடலுவகை": "The Pleasures of Temporary Variance"
};

export const adhigaramTransliterations: Record<string, string> = {
    "கடவுள் வாழ்த்து": "Kadavul Vazhthu",
    "வான்சிறப்பு": "Vaan Sirappu",
    "நீத்தார் பெருமை": "Neethar Perumai",
    "அறன் வலியுறுத்தல்": "Aran Valiyuruthal",
    "இல்வாழ்க்கை": "Ilvaazhkkai",
    "வாழ்க்கைத் துணைநலம்": "Vaazhkkai Thunainalam",
    "புதல்வரைப் பெறுதல்": "Pudhalvarai Perudhal",
    "அன்புடைமை": "Anbudaimai",
    "விருந்தோம்பல்": "Virundhombal",
    "இனியவை கூறல்": "Iniyavai Kooral",
    "செய்நன்றி அறிதல்": "Seinandri Arithal",
    "நடுவு நிலைமை": "Naduvu Nilaimai",
    "அடக்க முடைமை": "Adakkamudaimai",
    "ஒழுக்க முடைமை": "Ozhukkamudaimai",
    "பிறனில் விழையாமை": "Piranil Vizhaiyaamai",
    "பொறையுடைமை": "Poraiyudaimai",
    "அழுக்காறாமை": "Azhukkaaraamai",
    "வெஃகாமை": "Vekkhaamai",
    "புறங்கூறாமை": "Purangkooraamai",
    "பயனில சொல்லாமை": "Payanila Sollaamai",
    "தீவினையச்சம்": "Theevinaiyachcham",
    "ஒப்புரவறிதல்": "Oppuravarithal",
    "ஈகை": "Eegai",
    "புகழ்": "Pugazh",
    "அருளுடைமை": "Aruludaimai",
    "புலாலான் மறுத்தல்": "Pulaalaan Maruththal",
    "தவம்": "Thavam",
    "கூடாவொழுக்கம்": "Koodaavozhukkam",
    "கள்ளாமை": "Kallaamai",
    "வாய்மை": "Vaaimai",
    "வெகுளாமை": "Vegulaamai",
    "இன்னா செய்யாமை": "Innaa Seiyaamai",
    "கொல்லாமை": "Kollaamai",
    "நிலையாமை": "Nilaiyaamai",
    "துறவு": "Thuravu",
    "மெய்யுணர்தல்": "Meiyunardhal",
    "அவாஅறுத்தல்": "Avaa Aruththal",
    "ஊழ்": "Oozh",
    "இறைமாட்சி": "Iraimaatchi",
    "கல்வி": "Kalvi",
    "கல்லாமை": "Kallaamai",
    "கேள்வி": "Kelvi",
    "அறிவுடைமை": "Arivudaimai",
    "குற்றம் கடிதல்": "Kutram Kadidhal",
    "பெரியாரைத் துணைக்கோடல்": "Periyaarai Thunaikkodal",
    "சிற்றினம் சேராமை": "Sitrinam Seraamai",
    "தெரிந்து செயல்வகை": "Therindhu Seyalvagai",
    "வலியறிதல்": "Valiyaridhal",
    "காலமறிதல்": "Kaalamaridhal",
    "இடனறிதல்": "Idanaridhal",
    "தெரிந்து தெளிதல்": "Therindhu Thelidhal",
    "தெரிந்து வினையாடல்": "Therindhu Vinaiyaadal",
    "சுற்றந் தழால்": "Sutrandhazhaal",
    "பொச்சாவாமை": "Pochchaavaamai",
    "செங்கோன்மை": "Sengonmai",
    "கொடுங்கோன்மை": "Kodungonmai",
    "வெருவந்த செய்யாமை": "Veruvandha Seiyaamai",
    "கண்ணோட்டம்": "Kannottam",
    "ஒற்றாடல்": "Otraadal",
    "ஊக்கம் உடைமை": "Ookkamudaimai",
    "மடியின்மை": "Madiyinmai",
    "ஆள்வினையுடைமை": "Aalvinaiyudaimai",
    "இடுக்கண் அழியாமை": "Idukkan Azhiyaamai",
    "அமைச்சு": "Amaichu",
    "சொல்வன்மை": "Solvanmai",
    "வினைத் தூய்மை": "Vinai Thooymai",
    "வினைத்திட்பம்": "Vinai Thitpam",
    "வினைசெயல்வகை": "Vinai Seyalvagai",
    "தூது": "Thoodhu",
    "மன்னரைச் சேர்ந்தொழுகல்": "Mannarai Serndhozhugal",
    "குறிப்பறிதல்": "Kuripparidhal",
    "அவையறிதல்": "Avaiyaridhal",
    "அவை அஞ்சாமை": "Avai Anjaamai",
    "நாடு": "Naadu",
    "அரண்": "Aran",
    "பொருள்செயல்வகை": "Porul Seyalvagai",
    "படைமாட்சி": "Padai Maatchi",
    "படைச்செருக்கு": "Padai Serukku",
    "நட்பு": "Natpu",
    "நட்பாராய்தல்": "Natpaaraaidhal",
    "பழைமை": "Pazhaimai",
    "தீநட்பு": "Thee Natpu",
    "கூடாநட்பு": "Koodaa Natpu",
    "பேதைமை": "Pedhaimai",
    "புல்லறிவாண்மை": "Pullarivaanmai",
    "இகல்": "Igal",
    "பகைமாட்சி": "Pagaimaatchi",
    "பகைத்திறம் தெரிதல்": "Pagaithiram Theridhal",
    "உட்பகை": "Utpagai",
    "பெரியாரைப் பிழையாமை": "Periyaarai Pizhaiyaamai",
    "பெண்வழிச் சேறல்": "Pen Vazhi Seral",
    "வரைவின் மகளிர்": "Varaivin Magalir",
    "கள்ளுண்ணாமை": "Kallunnaamai",
    "சூது": "Soodhu",
    "மருந்து": "Marundhu",
    "குடிமை": "Kudimai",
    "மானம்": "Maanam",
    "பெருமை": "Perumai",
    "சான்றாண்மை": "Saandraanmai",
    "பண்புடைமை": "Panbudaimai",
    "நன்றியில் செல்வம்": "Nandriyil Selvam",
    "நாணுடைமை": "Naanudaimai",
    "குடிசெயல்வகை": "Kudi Seyalvagai",
    "உழவு": "Uzhavu",
    "நல்குரவு": "Nalkuravu",
    "இரவு": "Iravu",
    "இரவச்சம்": "Iravachcham",
    "கயமை": "Kayamai",
    "தகைஅணங்குறுத்தல்": "Thagai Anangurutthal",
    "புணர்ச்சி மகிழ்தல்": "Punarchchi Magizhdhal",
    "நலம் புனைந்து உரைத்தல்": "Nalam Punaindhu Uraiththal",
    "காதற் சிறப்புரைத்தல்": "Kaathar Sirappuraiththal",
    "நாணுத் துறவுரைத்தல்": "Naanu Thuravuraiththal",
    "அலரறிவுறுத்தல்": "Alar Arivuruththal",
    "பிரிவாற்றாமை": "Pirivaatraamai",
    "படர்மெலிந்திரங்கல்": "Padar Melindhirangal",
    "கண்விதுப்பழிதல்": "Kan Vithuppazhidhal",
    "பசப்புறுபருவரல்": "Pasappuruparuvaral",
    "தனிப்படர் மிகுதி": "Thani Padar Migudhi",
    "நினைந்தவர் புலம்பல்": "Ninaindhavar Pulambal",
    "கனவுநிலை உரைத்தல்": "Kanavu Nilai Uraiththal",
    "பொழுதுகண்டு இரங்கல்": "Pozhudhu Kandu Irangal",
    "உறுப்புநலன் அழிதல்": "Uruppu Nalan Azhidhal",
    "நெஞ்சொடு கிளத்தல்": "Nenjodu Kilaththal",
    "நிறையழிதல்": "Nirai Azhidhal",
    "அவர்வயின் விதும்பல்": "Avarvayin Vidhumbal",
    "குறிப்பறிவுறுத்தல்": "Kuripparivuruththal",
    "புணர்ச்சி விதும்பல்": "Punarchchi Vidhumbal",
    "நெஞ்சொடு புலத்தல்": "Nenjodu Pulaththal",
    "புலவி": "Pulavi",
    "புலவி நுணுக்கம்": "Pulavi Nunukkam",
    "ஊடலுவகை": "Oodaluvagai"
};
